spring:
  application:
    name: consultorio

  datasource:
    url: jdbc:mysql://localhost:3306/kosmos
    username: root
    password: SendoHammon1@

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto:update